#!/bin/sh

set -e

echo "Setting USB 3.0 port to host mode"
test -e /sys/devices/usb.1/12000000.dwc3/id && echo 0 > /sys/devices/usb.1/12000000.dwc3/id

test -e /usr/bin/resin-530s-spidev && /usr/bin/resin-530s-spidev
test -e /usr/bin/resin-530s-i2c1 && /usr/bin/resin-530s-i2c1

exit 0
